In [2]:
import pandas as pd
import numpy as np

In [7]:
data = pd.Series(
    np.random.randn(9),
    index=[
        ['a','a','a','b','b','c','c','d','d'],
        [1,2,3,1,3,1,2,2,3]
    ]
)

print(data)

a  1   -0.095632
   2    1.655961
   3   -0.262909
b  1    1.313269
   3    0.253098
c  1   -0.090967
   2   -1.089645
d  2   -2.082038
   3    0.229561
dtype: float64

In [8]:
print(data.index)

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [9]:
print(data['b'])
print(data['b':'c'])
print(data.loc[['b','d']])

1    1.313269
3    0.253098
dtype: float64
b  1    1.313269
   3    0.253098
c  1   -0.090967
   2   -1.089645
dtype: float64
b  1    1.313269
   3    0.253098
d  2   -2.082038
   3    0.229561
dtype: float64

In [10]:
print(data.loc[:,2])

a    1.655961
c   -1.089645
d   -2.082038
dtype: float64

In [11]:
print(data.unstack())

          1         2         3
a -0.095632  1.655961 -0.262909
b  1.313269       NaN  0.253098
c -0.090967 -1.089645       NaN
d       NaN -2.082038  0.229561

In [12]:
print(data.unstack().stack())

a  1   -0.095632
   2    1.655961
   3   -0.262909
b  1    1.313269
   2         NaN
   3    0.253098
c  1   -0.090967
   2   -1.089645
   3         NaN
d  1         NaN
   2   -2.082038
   3    0.229561
dtype: float64

In [13]:
frame = pd.DataFrame(
    np.arange(12).reshape((4,3)),
    index=[['a','a','b','b'], [1,2,1,2]],
    columns=[['Ohio','Ohio','Colorado'],
             ['Green','Red','Green']]
)

print(frame)

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [14]:
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']

print(frame)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [15]:
print(frame['Ohio'])

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [16]:
col_index = pd.MultiIndex.from_arrays(
    [['Ohio','Ohio','Colorado'],
     ['Green','Red','Green']],
    names=['state','color']
)

print(col_index)

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

In [17]:
print(frame.swaplevel('key1','key2'))

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [18]:
print(frame.sort_index(level=1))

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [19]:
print(frame.swaplevel(0,1).sort_index(level=0))

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [23]:
print(frame.groupby(level='key1').sum())

state  Ohio     Colorado
color Green Red    Green
key1
a         3   5        7
b        15  17       19

In [29]:
print(frame.T.groupby(level='color').sum().T)

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [30]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),                     
'c': ['one', 'one', 'one', 'two', 'two','two', 'two'],
'd': [0, 1, 2, 0, 1, 2, 3]})
print(frame)

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [31]:
frame.set_index(['c', 'd'], drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [32]:
frame.reset_index()

   index  a  b    c  d
0      0  0  7  one  0
1      1  1  6  one  1
2      2  2  5  one  2
3      3  3  4  two  0
4      4  4  3  two  1
5      5  5  2  two  2
6      6  6  1  two  3

In [34]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [36]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [37]:
pd.merge(df1, df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [42]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})

In [43]:
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [44]:
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [45]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [46]:
pd.merge(df1, df2, how='outer')

  key  data1  data2
0   a    2.0    0.0
1   a    4.0    0.0
2   a    5.0    0.0
3   b    0.0    1.0
4   b    1.0    1.0
5   b    6.0    1.0
6   c    3.0    NaN
7   d    NaN    2.0

In [47]:
pd.merge(df1, df2, on='key', how='left')

  key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [48]:
pd.merge(df1, df2, how='inner')

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1